START TRANSACTION;


INSERT INTO `organizations` (`name`,`abbreviation`, `description`) 
VALUES ('eCitizen','ecitizen', 'eCitizen ensures that Citizens, non-Citizens and Business entities can access Government Services online and make Payments electronically and conveniently, using their preferred method of payment, 24 hours a day and from wherever they may be in the world'),
('World Bank','World Bank','The World Bank is an international financial institution that provides loans and grants to the governments of poorer countries for the purpose of pursuing capital projects. It comprises two institutions: the International Bank for Reconstruction and Development (IBRD), and the International Development Association (IDA). The World Bank is a component of the World Bank Group.'),
('United Nations','UN', 'The United Nations is an international organization founded in 1945. It is currently made up of 193 Member States. The mission and work of the United Nations are guided by the purposes and principles contained in its founding Charter.'),
('International Monetary Fund','IMF', 'The International Monetary Fund (IMF) is an international organization headquartered in Washington, D.C., consisting of 190 countries working to foster global monetary cooperation, secure financial stability, facilitate international trade, promote high employment and sustainable economic growth, and reduce poverty around the world.'),
('African Union','AU', 'The African Union (AU) is a continental body consisting of the 55 member states that make up the countries of the African Continent. It was officially launched in Durban, South Africa, on 9 July 2002.'),
('European Union','EU', 'The European Union (EU) is a political and economic union of 27 member states that are located primarily in Europe. Its members have a combined area of 4,233,255.3 km² and an estimated total population of about 447 million. The EU has developed an internal single market through a standardised system of laws that apply in all member states in those matters, and only those matters, where members have agreed to act as one.'),
('East African Community','EAC', 'The East African Community (EAC) is an intergovernmental organization composed of six countries in the African Great Lakes region in eastern Africa: Burundi, Kenya, Rwanda, South Sudan, Tanzania, and Uganda. '),
('Common Market for Eastern and Southern Africa','COMESA', 'The Common Market for Eastern and Southern Africa (COMESA) is a free trade area with twenty-one member states located in Eastern and Southern Africa. '),
('Economic Community of West African States','ECOWAS', 'The Economic Community of West African States (ECOWAS) is a regional political and economic union of fifteen countries located in West Africa. '),
('Southern African Development Community','SADC', 'The Southern African Development Community (SADC) is an inter-governmental organization headquartered in Gaborone, Botswana. Its goal is to further socio-economic cooperation and integration as well as political and security cooperation among 16 southern African states.'),
('Arab League','AL', 'The Arab League, formally the League of Arab States, is a regional organization in the Arab world, which is located in Africa and Western Asia. '),
('Commonwealth of Nations','Commonwealth', 'The Commonwealth of Nations, generally known simply as the Commonwealth, is a political association of 54 member states, nearly all of them former territories of the British Empire. '),
('Organization of Islamic Cooperation','OIC', 'The Organisation of Islamic Cooperation is an international organization founded in 1969, consisting of 57 member states, with a collective population of over 1.8 billion as of 2015 with 53 countries being Muslim-majority countries. '),
('North Atlantic Treaty Organization','NATO', 'The North Atlantic Treaty Organization, also called the North Atlantic Alliance, is an intergovernmental military alliance between 30 North American and European countries. '),
('World Health Organization','WHO', 'The World Health Organization is a specialized agency of the United Nations responsible for international public health. '),
('United Nations Educational, Scientific and Cultural Organization','UNESCO', 'The United Nations Educational, Scientific and Cultural Organization is a specialized agency of the United Nations aimed at promoting world peace and security through international cooperation in education, the sciences, and culture. '),
('United Nations Children''s Fund','UNICEF', 'The United Nations Children''s Fund is a United Nations agency responsible for providing humanitarian and developmental aid to children worldwide.'),
('United Nations High Commissioner for Refugees','UNHCR', 'The Office of the United Nations High Commissioner for Refugees is a United Nations agency with the mandate to protect refugees, forcibly displaced communities, and stateless people, and assist in their voluntary repatriation, local integration, or resettlement to a third country. '),
('United Nations Development Programme','UNDP', 'The United Nations Development Programme is the United Nations'' global development network. It advocates for change and connects countries to knowledge, experience, and resources to help people build a better life. '),
('United Nations Population Fund','UNFPA', 'The United Nations Population Fund, formerly the United Nations Fund for Population Activities, is a UN agency aimed at improving reproductive and maternal health worldwide. '),
('United Nations Office for Project Services','UNOPS', 'The United Nations Office for Project Services is an operational arm of the United Nations, dedicated to implementing projects for the United Nations System, international financial institutions, governments, and other partners around the world. '),
('United Nations Office on Drugs and Crime','UNODC', 'The United Nations Office on Drugs and Crime is a United Nations office that was established in 1997 as the Office for Drug Control and Crime Prevention by combining the United Nations International Drug Control Program (UNDCP) and the Crime Prevention and Criminal Justice Division in the United Nations Office at Vienna. '),
('United Nations Environment Programme','UNEP', 'The United Nations Environment Programme is responsible for coordinating the UN''s environmental activities and assisting developing countries in implementing environmentally sound policies and practices. '),
('United Nations Human Settlements Programme','UN-Habitat', 'The United Nations Human Settlements Programme is the United Nations programme for human settlements and sustainable urban development. It was established in 1978 as an outcome of the First UN Conference on Human Settlements and Sustainable Urban Development (Habitat I) held in Vancouver, Canada in 1976.'),
('Finanical Sector Deepening Africa','FSD Africa', 'FSD Africa is a specialist development agency working to reduce poverty by strengthening financial markets across sub-Saharan Africa. '),
('Deutsche Gesellschaft für Internationale Zusammenarbeit','GIZ', 'GmbH is Germany''s leading provider of international cooperation services. As a federal enterprise, we support the German Government in achieving its objectives in the field of international cooperation for sustainable development.'),

('Safaricom','Safaricom', 'Safaricom is a leading communications company in Kenya with the widest and strongest coverage. '),
('Airtel','Airtel', 'Airtel Africa is a leading provider of telecommunications and mobile money services, with a presence in 14 countries in Africa, primarily in East Africa and Central and West Africa. '),
('Telkom Kenya','Telkom', 'Telkom Kenya is the sole provider of landline phone services in Kenya. '),
('Equity Bank','Equity', 'Equity Bank is a financial services provider headquartered in Nairobi, Kenya. '),
('Cooperative Bank of Kenya','Co-op Bank', 'Co-operative Bank of Kenya is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Standard Chartered Bank','StanChart', 'Standard Chartered Bank Kenya Limited is a commercial bank in Kenya. '),
('Absa','Absa', 'Absa Bank Kenya PLC, formerly Barclays Bank of Kenya Limited, is a commercial bank in Kenya and a subsidiary of South Africa-based Absa Group Limited. '),
('National Bank of Kenya','National Bank', 'National Bank of Kenya is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Kenya Commercial Bank','KCB', 'KCB Bank Kenya Limited is a financial services provider headquartered in Nairobi, Kenya. '),
('Citi Bank','Citi', 'Citibank Kenya is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Chase Bank','Chase', 'Chase Bank Kenya Limited, commonly referred to as Chase Bank, was a commercial bank in Kenya, licensed by the Central Bank of Kenya, the central bank and national banking regulator. '),
('Family Bank','Family Bank', 'Family Bank Limited, commonly known as Family Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Sidian Bank','Sidian', 'Sidian Bank Limited, formerly known as K-Rep Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Jamii Bora Bank','Jamii Bora', 'Jamii Bora Bank Limited, commonly referred to as Jamii Bora Bank, is a commercial bank in Kenya, licensed by the Central Bank of Kenya, the central bank and national banking regulator. '),
('Prime Bank','Prime', 'Prime Bank Limited, commonly known as Prime Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Credit Bank','Credit', 'Credit Bank Limited, commonly known as Credit Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Equatorial Commercial Bank','Equatorial', 'Equatorial Commercial Bank Limited, commonly known as Equatorial Commercial Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Consolidated Bank','Consolidated', 'Consolidated Bank of Kenya Limited, commonly known as Consolidated Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Imperial Bank','Imperial', 'Imperial Bank Limited, commonly known as Imperial Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Gulf African Bank','Gulf', 'Gulf African Bank Limited, commonly known as Gulf African Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Housing Finance Company of Kenya','HFC', 'commonly known as Housing Finance, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('I&M Bank','I&M', 'I&M Bank Limited, commonly known as I&M Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Middle East Bank','Middle East', 'Middle East Bank Kenya Limited, commonly known as Middle East Bank, is a commercial bank in Kenya, the largest economy in the East African Community. '),
('Amazon Web Services','AWS', 'Amazon Web Services is a subsidiary of Amazon providing on-demand cloud computing platforms and APIs to individuals, companies, and governments, on a metered pay-as-you-go basis. '),
('META','META', 'META is a technology company that builds and deploys digital solutions for governments and businesses. '),
('Google','Google', 'Google is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. '),
('Microsoft','Microsoft', 'Microsoft Corporation is an American multinational technology company with headquarters in Redmond, Washington. It develops, manufactures, licenses, supports, and sells computer software, consumer electronics, personal computers, and related services. '),
('Oracle','Oracle', 'Oracle Corporation is an American multinational computer technology corporation headquartered in Redwood Shores, California. '),
('IBM','IBM', 'International Business Machines Corporation is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. '),
('VISA','VISA', 'Visa Inc. is an American multinational financial services corporation headquartered in Foster City, California, United States. '),
('Mastercard','Mastercard', 'Mastercard Incorporated is an American multinational financial services corporation headquartered in the Mastercard International Global Headquarters in Purchase, New York, United States. '),
('ECS','ECS', 'ECS is a technology company that builds and deploys digital solutions for governments and businesses. '),
('ESDEV','ESDEV','Pan-African Non-Governmental Organization committed to promoting quality education and skills development, innovative research');


INSERT INTO `roles` (`name`,`description`) VALUES 
('admin', 'A user with superuser system-wide access privileges'),
('user', 'A user with limited system access privileges') ;

INSERT INTO `users` (`first_name`,`last_name`,`organization`,`designation`,`email`,`phone`,`password`) VALUES 
('Maxwel', 'Barno', 'eCitizen', 'System Administrator', 'admin@ecitizen.go.ke', '0708223344','$pbkdf2-sha256$29000$B8DY29s7J0SodQ4hBEAIQQ$K8KgsYhCXdlk8yw9jJwkNaV8QecaQxSqHLHoLQuWyEY');

INSERT INTO `users_roles` (`user_id`, `role_id`) VALUES (1, 1);

INSERT INTO `locations` (`county`, `town`) VALUES
('Baringo', 'Kabarnet'),
('Bomet', 'Bomet'),
('Bungoma', 'Malakisi'),
('Busia', 'Nambale'),
('Elgeyo-Marakwet', 'Iten'),
('Embu', 'Embu'),
('Garissa', 'Garissa'),
('Homa Bay', 'Kendu Bay'),
('Isiolo', 'Isiolo'),
('Kajiado', 'Ongata Rongai'),
('Kakamega', 'Malava'),
('Kericho', 'Litein'),
('Kiambu', 'Juja'),
('Kilifi', 'Mtwapa'),
('Kirinyaga', 'Kerugoya'),
('Kisumu', 'Airport'),
('Kitui', 'Kitui'),
('Kwale', 'Kwale'),
('Laikipia', 'Nyahururu'),
('Lamu', 'Lamu'),
('Machakos', 'Mlolongo'),
('Makueni', 'Wote'),
('Mandera', 'Mandera'),
('Marsabit', 'Marsabit'),
('Meru', 'Meru'),
('Migori', 'Rongo'),
('Mombasa', 'Bamburi'),
('Murang\'a', 'Maragua'),
('Nairobi', 'Adams Arcade'),
('Nakuru', 'Molo'),
('Nandi', 'Nandi Hills'),
('Narok', 'Narok'),
('Nyamira', 'Nyansiongo'),
('Nyandarua', 'Ol Kalou'),
('Nyeri', 'Nyeri'),
('Samburu', 'Maralal'),
('Siaya', 'Ukwala'),
('Taita-Taveta', 'Taveta'),
('Tana River', 'Hola'),
('Tharaka-Nithi', 'Chuka'),
('Trans Nzoia', 'Kitale'),
('Turkana', 'Kakuma'),
('Uasin Gishu', 'Burnt forest'),
('Vihiga', 'Luanda'),
('Wajir', 'Wajir'),
('West Pokot', 'Kapenguria'),
('Baringo', 'Eldama Ravine'),
('Bomet', 'Longisa'),
('Bungoma', 'Bungoma'),
('Busia', 'Busia'),
('Embu', 'Runyenjes'),
('Homa Bay', 'Homa Bay'),
('Kajiado', 'Kajiado'),
('Kakamega', 'Kakamega'),
('Kericho', 'Kericho'),
('Kiambu', 'Kiambu'),
('Kilifi', 'Kilifi'),
('Kirinyaga', 'Sagana'),
('Kisumu', 'Akado'),
('Kitui', 'Mwingi'),
('Kwale', 'Ukunda'),
('Laikipia', 'Nanyuki'),
('Machakos', 'Machakos'),
('Meru', 'Chuka'),
('Migori', 'Migori'),
('Mombasa', 'Bangala'),
('Murang\'a', 'Murang\'a'),
('Nairobi', 'Airbase'),
('Nakuru', 'Nakuru'),
('Nandi', 'Kapsabet'),
('Narok', 'Kilgoris'),
('Nyamira', 'Nyamira'),
('Nyandarua', 'Engineer'),
('Nyeri', 'Karatina'),
('Siaya', 'Siaya'),
('Taita-Taveta', 'Voi'),
('Turkana', 'Lodwar'),
('Uasin Gishu', 'Eldoret'),
('Vihiga', 'Vihiga'),
('West Pokot', 'Kacheliba'),
('Baringo', 'Mogotio'),
('Bungoma', 'Webuye'),
('Busia', 'Malaba'),
('Homa Bay', 'Oyugis'),
('Kajiado', 'Ngong'),
('Kakamega', 'Mumias'),
('Kericho', 'Londiani'),
('Kiambu', 'Thika'),
('Kilifi', 'Malindi'),
('Kirinyaga', 'Kisii County:'),
('Kisumu', 'Amala'),
('Laikipia', 'Rumuruti'),
('Machakos', 'Athi River'),
('Meru', 'Maua'),
('Migori', 'Awendo'),
('Mombasa', 'Beach Road'),
('Murang\'a', 'Kenol'),
('Nairobi', 'Akiba'),
('Nakuru', 'Naivasha'),
('Nyamira', 'Keroka'),
('Siaya', 'Yala'),
('Taita-Taveta', 'Wundanyi'),
('Bungoma', 'Kimilili'),
('Homa Bay', 'Mbita'),
('Kajiado', 'Kitengela'),
('Kericho', 'Londiani'),
('Kiambu', 'Ruiru'),
('Kilifi', 'Watamu'),
('Kirinyaga', 'Suneka'),
('Kisumu', 'Angawa'),
('Machakos', 'Kangundo'),
('Mombasa', 'Bombolulu'),
('Nairobi', 'Athi River'),
('Nakuru', 'Gilgil'),
('Kiambu', 'Kikuyu'),
('Kilifi', 'Mariakani'),
('Kirinyaga', 'Kisii'),
('Kisumu', 'Arina'),
('Machakos', 'Matuu'),
('Mombasa', 'Bondeni'),
('Nairobi', 'Avondale'),
('Kiambu', 'Limuru'),
('Kirinyaga', 'Ogembo'),
('Kisumu', 'Awasi'),
('Mombasa', 'Buoy'),
('Nairobi', 'Baba Dogo'),
('Kiambu', 'Karuri'),
('Kirinyaga', 'Tabaka'),
('Kisumu', 'Bandani'),
('Mombasa', 'Changamwe'),
('Nairobi', 'Bahati'),
('Kisumu', 'Baraka'),
('Mombasa', 'Chaani'),
('Nairobi', 'Baraka'),
('Kisumu', 'Bofu'),
('Mombasa', 'Chakama'),
('Nairobi', 'Bellevue'),
('Kisumu', 'Car Wash'),
('Mombasa', 'Chamanzi'),
('Nairobi', 'Bertshire'),
('Kisumu', 'Central'),
('Mombasa', 'Chango Macho'),
('Nairobi', 'Blue Valley'),
('Kisumu', 'Champion'),
('Mombasa', 'Chidya'),
('Nairobi', 'Bogani'),
('Kisumu', 'Chiga'),
('Mombasa', 'Chumani'),
('Nairobi', 'Bomas of Kenya'),
('Kisumu', 'College'),
('Mombasa', 'Cinemax'),
('Nairobi', 'Bondeni'),
('Kisumu', 'Diamond'),
('Mombasa', 'City Centre'),
('Nairobi', 'Buruburu'),
('Kisumu', 'Domus'),
('Mombasa', 'Docks'),
('Nairobi', 'Cabanas'),
('Kisumu', 'Eastleigh'),
('Mombasa', 'Frere Town'),
('Nairobi', 'California'),
('Kisumu', 'Eden Rock'),
('Mombasa', 'Ganjoni'),
('Nairobi', 'Capitol Hill'),
('Kisumu', 'Elysee'),
('Mombasa', 'Gede'),
('Nairobi', 'CBD (al Business District)'),
('Kisumu', 'Flamingo'),
('Mombasa', 'Gikoni'),
('Nairobi', 'Chiromo'),
('Kisumu', 'Fort Jesus'),
('Mombasa', 'Gotani'),
('Nairobi', 'City Park'),
('Kisumu', 'Gudka'),
('Mombasa', 'Grogan'),
('Nairobi', 'Clay City'),
('Kisumu', 'Habitat'),
('Mombasa', 'Gudka'),
('Nairobi', 'Coffee Gardens'),
('Kisumu', 'Imara'),
('Mombasa', 'Guraya'),
('Nairobi', 'Comm 19'),
('Kisumu', 'Impala'),
('Mombasa', 'Halisi'),
('Nairobi', 'Dagoretti'),
('Kisumu', 'Industrial Area'),
('Mombasa', 'Kaa Chonjo'),
('Nairobi', 'Dam Estate'),
('Kisumu', 'Jalaram'),
('Mombasa', 'Kajembe'),
('Nairobi', 'Dandora'),
('Kisumu', 'Kanyakwar'),
('Mombasa', 'Kakamega'),
('Nairobi', 'DC (matic Corps) area'),
('Kisumu', 'Kanyakwar B'),
('Mombasa', 'Kaloleni'),
('Nairobi', 'Deep Sea'),
('Kisumu', 'Kanyakwar C'),
('Mombasa', 'Kanduyi'),
('Nairobi', 'Diamond Park'),
('Kisumu', 'Kanyakwar D'),
('Mombasa', 'Kiembeni'),
('Nairobi', 'Donholm'),
('Kisumu', 'Kanyakwar E'),
('Mombasa', 'Kilifi'),
('Nairobi', 'Doonholm'),
('Kisumu', 'Kibos'),
('Mombasa', 'Kisauni'),
('Nairobi', 'Eastleigh'),
('Kisumu', 'Kibuye'),
('Mombasa', 'Kizingo'),
('Nairobi', 'Eastlands'),
('Kisumu', 'Kibuye Market'),
('Mombasa', 'Kongowea'),
('Nairobi', 'Eastleigh North'),
('Kisumu', 'Kondele'),
('Mombasa', 'Kwa Shibu'),
('Nairobi', 'Eastleigh South'),
('Kisumu', 'Konditi'),
('Mombasa', 'Kwale'),
('Nairobi', 'Eastleigh Section 1'),
('Kisumu', 'Lake View'),
('Mombasa', 'Likoni'),
('Nairobi', 'Eastleigh Section 2'),
('Kisumu', 'Lake View Phase 1'),
('Mombasa', 'Lumumba'),
('Nairobi', 'Eastleigh Section 3'),
('Kisumu', 'Lake View Phase 2'),
('Mombasa', 'Majaoni'),
('Nairobi', 'Eastleigh Section 4'),
('Kisumu', 'Lela'),
('Mombasa', 'Majengo'),
('Nairobi', 'Eastleigh Section 5'),
('Kisumu', 'Lichota'),
('Mombasa', 'Maji ya Chumvi'),
('Nairobi', 'Eastleigh Section 6'),
('Kisumu', 'Ligo'),
('Mombasa', 'Makande'),
('Nairobi', 'Eastleigh Section 7'),
('Kisumu', 'Lolwe'),
('Mombasa', 'Makupa'),
('Nairobi', 'Eastleigh Section 8'),
('Kisumu', 'Lower Milimani'),
('Mombasa', 'Malindi'),
('Nairobi', 'Eastleigh Section 9'),
('Kisumu', 'Lumumba'),
('Mombasa', 'Mariakani'),
('Nairobi', 'Eastleigh Section 10'),
('Kisumu', 'Manyatta'),
('Mombasa', 'Masjid Musa'),
('Nairobi', 'Eastleigh Section 11'),
('Kisumu', 'Mamboleo'),
('Mombasa', 'Mbonga'),
('Nairobi', 'Eastleigh Section 12'),
('Kisumu', 'Manyatta A'),
('Mombasa', 'Memon'),
('Nairobi', 'Eastleigh Section 13'),
('Kisumu', 'Manyatta B'),
('Mombasa', 'Miritini'),
('Nairobi', 'Eastleigh Section 14'),
('Kisumu', 'Manyatta C'),
('Mombasa', 'Mishomoroni'),
('Nairobi', 'Eastleigh Section 15'),
('Kisumu', 'Manyatta D'),
('Mombasa', 'Mkomani'),
('Nairobi', 'Eastleigh Section 16'),
('Kisumu', 'Manyatta E'),
('Mombasa', 'Moi Avenue'),
('Nairobi', 'Eastleigh Section 17'),
('Kisumu', 'Migosi'),
('Mombasa', 'Mombasa Island'),
('Nairobi', 'Eastleigh Section 18'),
('Kisumu', 'Migosi Estate'),
('Mombasa', 'Mtongwe'),
('Nairobi', 'Eastleigh Section 19'),
('Kisumu', 'Migosi Phase 1'),
('Mombasa', 'Mtwapa'),
('Nairobi', 'Eastleigh Section 20'),
('Kisumu', 'Migosi Phase 2'),
('Mombasa', 'Mvita'),
('Nairobi', 'Eastleigh Section 21'),
('Kisumu', 'Migosi Phase 3'),
('Mombasa', 'Mwandoni'),
('Nairobi', 'Eastleigh Section 22'),
('Kisumu', 'Milimani'),
('Mombasa', 'Mzizima'),
('Nairobi', 'Eastleigh Section 23'),
('Kisumu', 'Milimani Phase 1'),
('Mombasa', 'Nairobi Area'),
('Nairobi', 'Eastleigh Section 24'),
('Kisumu', 'Milimani Phase 2'),
('Mombasa', 'Nakumatt Likoni'),
('Nairobi', 'Eastleigh Section 25'),
('Kisumu', 'Milimani Phase 3'),
('Mombasa', 'Ndia Kuu'),
('Nairobi', 'Eastleigh Section 26'),
('Kisumu', 'Mowlem'),
('Mombasa', 'Nguu Tatu'),
('Nairobi', 'Eastleigh Section 27'),
('Kisumu', 'Muhoroni'),
('Mombasa', 'Njia Panda'),
('Nairobi', 'Eastleigh Section 28'),
('Kisumu', 'Nanga'),
('Mombasa', 'North Coast'),
('Nairobi', 'Eastleigh Section 29'),
('Kisumu', 'Nyalenda'),
('Mombasa', 'Nyali'),
('Nairobi', 'Eastleigh Section 30'),
('Kisumu', 'Nyaluoyo'),
('Mombasa', 'Old Town'),
('Nairobi', 'Eastleigh Section 31'),
('Kisumu', 'Nyamasaria'),
('Mombasa', 'Pandya'),
('Nairobi', 'Eastleigh Section 32'),
('Kisumu', 'Nyamasaria Estate'),
('Mombasa', 'Pembe za Ndovu'),
('Nairobi', 'Eastleigh Section 33'),
('Kisumu', 'Nyamasaria Phase 1'),
('Mombasa', 'Port Reitz'),
('Nairobi', 'Eastleigh Section 34'),
('Kisumu', 'Nyamasaria Phase 2'),
('Mombasa', 'Sabaki'),
('Nairobi', 'Eastleigh Section 35'),
('Kisumu', 'Nyamasaria Phase 3'),
('Mombasa', 'Saba Saba'),
('Nairobi', 'Eastleigh Section 36'),
('Kisumu', 'Nyamasaria Phase 4'),
('Mombasa', 'Shanzu'),
('Nairobi', 'Eastleigh Section 37'),
('Kisumu', 'Nyawita'),
('Mombasa', 'Shauri Yako'),
('Nairobi', 'Eastleigh Section 38'),
('Kisumu', 'Otonglo'),
('Mombasa', 'South Coast'),
('Nairobi', 'Eastleigh Section 39'),
('Kisumu', 'Pandpieri'),
('Mombasa', 'Stadium Area'),
('Nairobi', 'Eastleigh Section 40'),
('Kisumu', 'Riat'),
('Mombasa', 'Taita'),
('Nairobi', 'Eastleigh Section 41'),
('Kisumu', 'Riat Estate'),
('Mombasa', 'Taru'),
('Nairobi', 'Eastleigh Section 42'),
('Kisumu', 'Riat Hills'),
('Mombasa', 'Tassia'),
('Nairobi', 'Eastleigh Section 43'),
('Kisumu', 'Riat Hills Phase 1'),
('Mombasa', 'Tudor'),
('Nairobi', 'Eastleigh Section 44'),
('Kisumu', 'Riat Hills Phase 2'),
('Mombasa', 'Uviringo'),
('Nairobi', 'Eastleigh Section 45'),
('Kisumu', 'Riat Phase 1'),
('Mombasa', 'Uwanja Wa Mbuzi'),
('Nairobi', 'Eastleigh Section 46'),
('Kisumu', 'Riat Phase 2'),
('Mombasa', 'Vijana'),
('Nairobi', 'Eastleigh Section 47'),
('Kisumu', 'Sango'),
('Mombasa', 'Vipingo'),
('Nairobi', 'Eastleigh Section 48'),
('Kisumu', 'Shauri Moyo'),
('Nairobi', 'Eastleigh Section 49'),
('Kisumu', 'Sinyolo'),
('Nairobi', 'Eastleigh Section 50'),
('Kisumu', 'Sosiani'),
('Nairobi', 'Eastleigh Section 51'),
('Kisumu', 'Tassia'),
('Nairobi', 'Eastleigh Section 52'),
('Kisumu', 'Tom Mboya'),
('Nairobi', 'Eastleigh Section 53'),
('Kisumu', 'Tom Mboya Estate'),
('Nairobi', 'Eastleigh Section 54'),
('Kisumu', 'United'),
('Nairobi', 'Eastleigh Section 55'),
('Kisumu', 'Uzima'),
('Nairobi', 'Eastleigh Section 56'),
('Nairobi', 'Eastleigh Section 57'),
('Nairobi', 'Eastleigh Section 58'),
('Nairobi', 'Eastleigh Section 59'),
('Nairobi', 'Eastleigh Section 60'),
('Nairobi', 'Eastleigh Section 61'),
('Nairobi', 'Eastleigh Section 62'),
('Nairobi', 'Eastleigh Section 63'),
('Nairobi', 'Eastleigh Section 64'),
('Nairobi', 'Eastleigh Section 65'),
('Nairobi', 'Eastleigh Section 66'),
('Nairobi', 'Eastleigh Section 67'),
('Nairobi', 'Eastleigh Section 68'),
('Nairobi', 'Eka Hotel'),
('Nairobi', 'Embakasi'),
('Nairobi', 'Emeryville'),
('Nairobi', 'Fadhili Estate'),
('Nairobi', 'Fedha Estate'),
('Nairobi', 'Fortis Towers'),
('Nairobi', 'Fourways Junction'),
('Nairobi', 'Garden Estate'),
('Nairobi', 'Gataka Road'),
('Nairobi', 'Gatina'),
('Nairobi', 'Gichagi'),
('Nairobi', 'Gikomba'),
('Nairobi', 'Githurai'),
('Nairobi', 'Green Park'),
('Nairobi', 'Greenspan Estate'),
('Nairobi', 'Hamza'),
('Nairobi', 'Hardy'),
('Nairobi', 'High Ridge'),
('Nairobi', 'Hill View'),
('Nairobi', 'Hurlingham'),
('Nairobi', 'Imara Daima'),
('Nairobi', 'Jamhuri Estate'),
('Nairobi', 'Jamia'),
('Nairobi', 'Jogoo Road'),
('Nairobi', 'Kabete'),
('Nairobi', 'Kahawa Sukari'),
('Nairobi', 'Kahawa Wendani'),
('Nairobi', 'Karen'),
('Nairobi', 'Karen Blixen'),
('Nairobi', 'Kariobangi'),
('Nairobi', 'Kasarani'),
('Nairobi', 'Kawangware'),
('Nairobi', 'Kenya Re Towers'),
('Nairobi', 'Kibera'),
('Nairobi', 'Kileleshwa'),
('Nairobi', 'Kilimani'),
('Nairobi', 'Kiota'),
('Nairobi', 'Kitisuru'),
('Nairobi', 'Kitusuru Estate'),
('Nairobi', 'Komarock'),
('Nairobi', 'Kshatriya Court'),
('Nairobi', 'Kwa Reuben'),
('Nairobi', 'Kwang\'amor'),
('Nairobi', 'Lang\'ata'),
('Nairobi', 'Langa\'ta Road'),
('Nairobi', 'Lavington'),
('Nairobi', 'Le\'mac'),
('Nairobi', 'Lenana'),
('Nairobi', 'Limuru Road'),
('Nairobi', 'Loresho'),
('Nairobi', 'Lower Kabete'),
('Nairobi', 'Lumumba Drive'),
('Nairobi', 'Madaraka Estate'),
('Nairobi', 'Makina'),
('Nairobi', 'Makongeni'),
('Nairobi', 'Marurui'),
('Nairobi', 'Mathare'),
('Nairobi', 'Maziwa'),
('Nairobi', 'Membley'),
('Nairobi', 'Milimani'),
('Nairobi', 'Mlolongo'),
('Nairobi', 'Mombasa Road'),
('Nairobi', 'Mountain View'),
('Nairobi', 'Mugumo Estate'),
('Nairobi', 'Muthaiga'),
('Nairobi', 'Muthaiga North'),
('Nairobi', 'Muthangari'),
('Nairobi', 'Mwiki'),
('Nairobi', 'Nairobi West'),
('Garissa', 'Ugunja'),
('Nairobi', 'Nairobi Hospital'),
('Garissa', 'bondo'),
('Nairobi', 'Nairobi Upper Hill'),
('Nairobi', 'Naivasha Road'),
('Nairobi', 'Nakumatt Ukay'),
('Nairobi', 'Ndenderu'),
('Nairobi', 'New Kasarani'),
('Nairobi', 'Ngara'),
('Nairobi', 'Ngong Road'),
('Nairobi', 'Ngumo'),
('Nairobi', 'Nyayo Estate'),
('Nairobi', 'Nyari'),
('Nairobi', 'Nyayo Highrise'),
('Nairobi', 'Ongata Rongai'),
('Nairobi', 'Pangani'),
('Nairobi', 'Parklands'),
('Nairobi', 'Pipeline'),
('Nairobi', 'Ridgeways'),
('Nairobi', 'Riruta'),
('Nairobi', 'Riverbank'),
('Nairobi', 'Riverside'),
('Nairobi', 'Roysambu'),
('Nairobi', 'Runda'),
('Nairobi', 'Sankara Hotel'),
('Nairobi', 'Shauri Moyo'),
('Nairobi', 'South B'),
('Nairobi', 'South C'),
('Nairobi', 'Spring Valley'),
('Nairobi', 'Starehe'),
('Nairobi', 'State House Road'),
('Nairobi', 'Sunvalley Estate'),
('Nairobi', 'Syokimau'),
('Nairobi', 'Thika Road'),
('Nairobi', 'Thome'),
('Nairobi', 'Tigoni'),
('Nairobi', 'Umoja'),
('Nairobi', 'Upper Hill'),
('Nairobi', 'Valley Arcade'),
('Nairobi', 'Valley View Estate'),
('Nairobi', 'Villa Franca Estate'),
('Nairobi', 'Village Market'),
('Nairobi', 'Waiyaki Way'),
('Nairobi', 'Westlands'),
('Nairobi', 'Wilson Airport'),
('Nairobi', 'Woodley'),
('Nairobi', 'Yaya Centre'),
('Nairobi', 'Zimmerman');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `locations`
--
-- ALTER TABLE `locations`
--   ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `locations`
--
-- ALTER TABLE `locations`
--   MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=508;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
